import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
    title: 'What is CAS? | Confirmation of Acceptance for Studies | UK Visa Glossary',
    description: 'CAS (Confirmation of Acceptance for Studies) is an electronic document issued by a UK university required for your Student Visa application. Learn about CAS validity, how to get it, and what to do if you lose it.',
    keywords: ['CAS UK', 'Confirmation of Acceptance for Studies', 'CAS number', 'UK student visa requirements', 'CAS interview'],
    alternates: {
        canonical: 'https://ai.eecglobal.com/glossary/cas',
    },
};

const structuredData = {
    "@context": "https://schema.org",
    "@graph": [
        {
            "@type": "DefinedTerm",
            "@id": "https://ai.eecglobal.com/glossary/cas#term",
            "name": "Confirmation of Acceptance for Studies (CAS)",
            "alternateName": "CAS Statement",
            "description": "An electronic document generated by the UK Home Office when a licensed student sponsor (university) agrees to sponsor your Tier 4 General Student Visa application.",
            "inDefinedTermSet": {
                "@type": "DefinedTermSet",
                "name": "EEC Study Abroad Glossary"
            }
        },
        {
            "@type": "FAQPage",
            "mainEntity": [
                {
                    "@type": "Question",
                    "name": "How long is a CAS valid for?",
                    "acceptedAnswer": {
                        "@type": "Answer",
                        "text": "A CAS is valid for 6 months from the date of issue. You must use it to apply for your student visa within this timeframe."
                    }
                },
                {
                    "@type": "Question",
                    "name": "Can I have multiple CAS numbers?",
                    "acceptedAnswer": {
                        "@type": "Answer",
                        "text": "Yes, you can hold offers from multiple universities, but you should only accept one and use that specific CAS number for your visa application. Using a CAS automatically invalidates others for visa purposes."
                    }
                }
            ]
        }
    ]
};

export default function CASPage() {
    return (
        <>
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
            />

            <nav className="bg-white dark:bg-slate-800 border-b border-slate-100 dark:border-slate-700 py-3">
                <div className="max-w-4xl mx-auto px-4">
                    <ol className="flex items-center gap-2 text-sm text-slate-500 dark:text-slate-400">
                        <li><Link href="/" className="hover:text-violet-600 dark:hover:text-violet-400">Home</Link></li>
                        <li><span className="mx-2">›</span></li>
                        <li><Link href="/glossary" className="hover:text-violet-600 dark:hover:text-violet-400">Glossary</Link></li>
                        <li><span className="mx-2">›</span></li>
                        <li className="text-slate-800 dark:text-slate-200 font-medium">CAS</li>
                    </ol>
                </div>
            </nav>

            <main className="max-w-4xl mx-auto px-4 py-12">
                <header className="mb-8">
                    <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300 text-xs font-bold uppercase tracking-wider mb-4">
                        🇬🇧 UK Student Visa
                    </div>
                    <h1 className="text-4xl font-bold text-slate-900 dark:text-white mb-6">
                        What is a CAS (Confirmation of Acceptance for Studies)?
                    </h1>
                    <p className="text-xl text-slate-600 dark:text-slate-300 leading-relaxed">
                        The <strong>Confirmation of Acceptance for Studies (CAS)</strong> is typically considered the most important document in your UK study journey. It isn't a physical certificate but a unique 14-digit reference number.
                    </p>
                </header>

                <section className="prose prose-slate dark:prose-invert max-w-none">
                    <div className="bg-indigo-50 dark:bg-indigo-950/30 border-l-4 border-indigo-500 p-6 rounded-r-xl my-8">
                        <h3 className="text-indigo-900 dark:text-indigo-100 font-bold text-lg m-0 mb-2">Why is CAS Critical?</h3>
                        <p className="text-indigo-800 dark:text-indigo-200 m-0">
                            You cannot apply for a UK Student Visa (formerly Tier 4) without a valid CAS number. It proves that a licensed UK university has unconditionally offered you a place and is willing to act as your immigration sponsor.
                        </p>
                    </div>

                    <h2>What Information Does a CAS Contain?</h2>
                    <ul>
                        <li><strong>Personal Details:</strong> Name, Date of Birth, Passport Number.</li>
                        <li><strong>Course Details:</strong> Course Title, Level (NQF Level 7 for Master's), Start/End Dates.</li>
                        <li><strong>Financial Data:</strong> Tuition Fees for the first year and how much you have already paid (Deposit).</li>
                        <li><strong>English Proficiency:</strong> How the university assessed your English (e.g., IELTS, Waiver).</li>
                    </ul>

                    <h2>The CAS Lifecycle</h2>
                    <ol>
                        <li><strong>Offer:</strong> You receive an Unconditional Offer from the university.</li>
                        <li><strong>Deposit:</strong> You pay the required tuition deposit.</li>
                        <li><strong>Pre-CAS Interview:</strong> The university may interview you to check credibility (EEC's AI tool helps here!).</li>
                        <li><strong>Draft CAS:</strong> You receive a draft to check for errors.</li>
                        <li><strong>Final CAS:</strong> The official number is issued for your visa application.</li>
                    </ol>

                    <div className="not-prose mt-12">
                        <div className="bg-gradient-to-r from-indigo-600 to-violet-600 rounded-2xl p-8 text-white text-center">
                            <h3 className="text-2xl font-bold mb-4">Prepare for your Pre-CAS Interview</h3>
                            <p className="mb-8 opacity-90 max-w-xl mx-auto">
                                Many universities conduct a rigorous "Pre-CAS Credibility Interview" before releasing your CAS.
                                Don't risk rejection. Practice with our free AI simulator.
                            </p>
                            <Link
                                href="/ukprecas"
                                className="inline-block bg-white text-indigo-600 font-bold px-8 py-4 rounded-xl hover:bg-slate-50 transition transform hover:-translate-y-1 shadow-lg"
                            >
                                Start Free CAS Interview Prep
                            </Link>
                        </div>
                    </div>
                </section>
            </main>
        </>
    );
}
